export const KMH_OPTIONS = [
  // --- Original Fun Prompts ---
  'Harry Styles',
  'Person on Your Left',
  'Your Uber Driver',
  'Your Ex',
  'Your Boss',
  'Your Celebrity Crush',
  'Your Best Friend',
  'Your Childhood Crush',
  'Your Neighbor',
  'The Person Who Texted You Last',
  'Your First Date',
  'Your High School Bully',
  'The Bartender',
  'Your Clone',
  'A Billionaire Octogenarian',
  'Your Favorite Teacher',
  'The Person on Your Right',
  'Your Landlord',
  'The Person Holding Your Drink',
  'A Random Stranger',
  'Your Therapist',
  'Your Gym Trainer',
  'The President',
  'Your Doppelgänger',
  'A Pirate Captain',
  'An Alien Visitor',

  // --- Famous/Controversial Global Figures ---
  'Kanye West',
  'Elon Musk',
  'Donald Trump',
  'Mark Zuckerberg',
  'Jeff Bezos',
  'Kim Kardashian',
  'Andrew Tate',
  'Joe Biden',
  'Vladimir Putin',
  'Greta Thunberg',
  'Prince Harry',
  'Meghan Markle',
  'Amber Heard',
  'Johnny Depp',
  'Will Smith',
  'Chris Rock',
  'Oprah Winfrey',

  // --- Indian Celebrities & Figures ---
  'Shah Rukh Khan',
  'Salman Khan',
  'Virat Kohli',
  'Deepika Padukone',
  'Priyanka Chopra',
  'Ranveer Singh',
  'Alia Bhatt',
  'Karan Johar',
  'Kangana Ranaut',
  'Narendra Modi',
  'Rahul Gandhi',
  'Mukesh Ambani',
  'Arnab Goswami',
  'Rakhi Sawant',
  'Urvashi Rautela',
  'Hardik Pandya',
  'MS Dhoni',
  'Katrina Kaif',
  'Kareena Kapoor',
  'Ranbir Kapoor',
  'Hrithik Roshan',
  'Aishwarya Rai',
  'Amitabh Bachchan',
  'Sunny Leone',
  'Badshah',
  'Yo Yo Honey Singh',
  'CarryMinati',
  'Bhuvan Bam',

  // --- Pop Culture Icons ---
  'Taylor Swift',
  'Beyoncé',
  'Rihanna',
  'Justin Bieber',
  'Ariana Grande',
  'Drake',
  'Nicki Minaj',
  'Cardi B',
  'Eminem',
  'Snoop Dogg',
  'Lady Gaga',
  'Britney Spears',
  'Miley Cyrus',
  'Selena Gomez',
  'Zendaya',
  'Tom Holland',
  'Timothée Chalamet',
  'Jenna Ortega',
  'Robert Downey Jr.',
  'Dwayne "The Rock" Johnson',
  'Leonardo DiCaprio',
  'Brad Pitt',
  'Angelina Jolie',
  'Jennifer Lawrence',
  'Margot Robbie',
  'Ryan Reynolds',
  'Scarlett Johansson',
  'Gal Gadot',
  'Henry Cavill',
  'Keanu Reeves',
  'Pedro Pascal',

  // --- Generic & Funny ---
  'A Flat Earther',
  'A Karen',
  'Your future self',
  'The person you hate the most',
  'A creepy clown',
  'Your crushs partner',
  'An OnlyFans model',
  'A Crypto Bro',
  'A TikTok Influencer',
  'A Vegan Activist',
  'A Discord Mod',
  'Florida Man',
  'An Instagram Baddie',
  'Your FBI Agent',
  'Santa Claus',
  'The Grinch',
  'Shrek',
];
