export const TABOO_CARDS = [
    // --- Original/Basic ---
    { word: 'Coffee', forbidden: ['Drink', 'Caffeine', 'Starbucks', 'Beans', 'Morning'] },
    { word: 'Beach', forbidden: ['Sand', 'Ocean', 'Sun', 'Summer', 'Waves'] },
    { word: 'Superman', forbidden: ['Adventures', 'Hero', 'Fly', 'Kryptonite', 'Clark'] },
    { word: 'iPhone', forbidden: ['Apple', 'Phone', 'Call', 'Siri', 'Steve Jobs'] },
    { word: 'Pizza', forbidden: ['Cheese', 'Pepperoni', 'Italy', 'Dough', 'Slice'] },
    { word: 'Guitar', forbidden: ['Strings', 'Music', 'Instrument', 'Play', 'Rock'] },
    { word: 'Vampire', forbidden: ['Blood', 'Dracula', 'Teeth', 'Bat', 'Twilight'] },
    { word: 'Instagram', forbidden: ['Photo', 'App', 'Like', 'Filter', 'Story'] },
    { word: 'Snowman', forbidden: ['Winter', 'Cold', 'Carrot', 'Frosty', 'White'] },
    { word: 'Library', forbidden: ['Books', 'Read', 'Quiet', 'Study', 'School'] },

    // --- Food & Drink ---
    { word: 'Burger', forbidden: ['Bun', 'Meat', 'McDonalds', 'Cheese', 'Fast Food'] },
    { word: 'Sushi', forbidden: ['Fish', 'Rice', 'Japan', 'Roll', 'Raw'] },
    { word: 'Chocolate', forbidden: ['Sweet', 'Candy', 'Dark', 'Milk', 'Bar'] },
    { word: 'Ice Cream', forbidden: ['Cold', 'Cone', 'Flavor', 'Scoop', 'Dessert'] },
    { word: 'Popcorn', forbidden: ['Movie', 'Corn', 'Butter', 'Salt', 'Kernel'] },
    { word: 'Spaghetti', forbidden: ['Pasta', 'Noodle', 'Italy', 'Sauce', 'Meatball'] },
    { word: 'Taco', forbidden: ['Mexican', 'Shell', 'Meat', 'Tuesday', 'Salsa'] },
    { word: 'Pancake', forbidden: ['Breakfast', 'Syrup', 'Flat', 'Stack', 'Waffle'] },
    { word: 'Salad', forbidden: ['Green', 'Healthy', 'Lettuce', 'Vegetable', 'Dressing'] },
    { word: 'Water', forbidden: ['Drink', 'Liquid', 'Clear', 'Thirsty', 'H2O'] },

    // --- Animals ---
    { word: 'Elephant', forbidden: ['Big', 'Trunk', 'Grey', 'Zoo', 'Africa'] },
    { word: 'Giraffe', forbidden: ['Tall', 'Neck', 'Spots', 'Animal', 'Leaf'] },
    { word: 'Penguin', forbidden: ['Bird', 'Cold', 'Ice', 'Fly', 'Tuxedo'] },
    { word: 'Lion', forbidden: ['King', 'Cat', 'Roar', 'Mane', 'Jungle'] },
    { word: 'Snake', forbidden: ['Long', 'Hiss', 'Reptile', 'Poison', 'Slither'] },
    { word: 'Monkey', forbidden: ['Banana', 'Tree', 'Climb', 'Ape', 'Tail'] },
    { word: 'Shark', forbidden: ['Ocean', 'Teeth', 'Fish', 'Bite', 'Jaws'] },
    { word: 'Kangaroo', forbidden: ['Jump', 'Pouch', 'Australia', 'Hop', 'Joey'] },
    { word: 'Zebra', forbidden: ['Stripes', 'Black', 'White', 'Horse', 'Africa'] },
    { word: 'Dinosaur', forbidden: ['Extinct', 'Jurassic', 'Rex', 'Fossil', 'Big'] },

    // --- Places ---
    { word: 'School', forbidden: ['Teacher', 'Student', 'Learn', 'Class', 'Study'] },
    { word: 'Hospital', forbidden: ['Doctor', 'Nurse', 'Sick', 'Medicine', 'Ambulance'] },
    { word: 'Airport', forbidden: ['Plane', 'Fly', 'Travel', 'Suitcase', 'Pilot'] },
    { word: 'Gym', forbidden: ['Exercise', 'Workout', 'Muscle', 'Weights', 'Run'] },
    { word: 'Cinema', forbidden: ['Movie', 'Film', 'Popcorn', 'Screen', 'Watch'] },
    { word: 'Park', forbidden: ['Grass', 'Play', 'Tree', 'Walk', 'Bench'] },
    { word: 'Moon', forbidden: ['Night', 'Space', 'Sky', 'Star', 'Apollo'] },
    { word: 'Paris', forbidden: ['France', 'Eiffel', 'City', 'Love', 'Tower'] },
    { word: 'Jail', forbidden: ['Prison', 'Arrest', 'Police', 'Cell', 'Crime'] },
    { word: 'Mars', forbidden: ['Planet', 'Red', 'Space', 'Alien', 'Elon'] },

    // --- Objects ---
    { word: 'Chair', forbidden: ['Sit', 'Seat', 'Legs', 'Table', 'Furniture'] },
    { word: 'Shoes', forbidden: ['Feet', 'Walk', 'Pair', 'Laces', 'Sock'] },
    { word: 'Umbrella', forbidden: ['Rain', 'Wet', 'Cover', 'Water', 'Open'] },
    { word: 'Key', forbidden: ['Lock', 'Door', 'Open', 'Metal', 'Car'] },
    { word: 'Bed', forbidden: ['Sleep', 'Pillow', 'Night', 'Mattress', 'Rest'] },
    { word: 'Computer', forbidden: ['Laptop', 'Screen', 'Type', 'Internet', 'Mouse'] },
    { word: 'Car', forbidden: ['Drive', 'Wheel', 'Road', 'Vehicle', 'Ride'] },
    { word: 'Clock', forbidden: ['Time', 'Watch', 'Tick', 'Hour', 'Wall'] },
    { word: 'Mirror', forbidden: ['Reflection', 'Look', 'Glass', 'Self', 'See'] },
    { word: 'Toilet', forbidden: ['Bathroom', 'Flush', 'Restroom', 'Paper', 'Potty'] },

    // --- People/Roles ---
    { word: 'Doctor', forbidden: ['Hospital', 'Medicine', 'Sick', 'Nurse', 'Health'] },
    { word: 'Teacher', forbidden: ['School', 'Student', 'Learn', 'Class', 'Professor'] },
    { word: 'Police', forbidden: ['Cop', 'Arrest', 'Badge', 'Law', 'Siren'] },
    { word: 'Baby', forbidden: ['Cry', 'Diaper', 'Small', 'Milk', 'Child'] },
    { word: 'Clown', forbidden: ['Circus', 'Funny', 'Red', 'Nose', 'Scary'] },
    { word: 'Pirate', forbidden: ['Ship', 'Sea', 'Eye', 'Patch', 'Treasure'] },
    { word: 'Ninja', forbidden: ['Japan', 'Sword', 'Sneak', 'Mask', 'Black'] },
    { word: 'King', forbidden: ['Queen', 'Crown', 'Royal', 'Ruler', 'Throne'] },
    { word: 'Ghost', forbidden: ['Scary', 'White', 'Boo', 'Dead', 'Spirit'] },
    { word: 'Robot', forbidden: ['Machine', 'AI', 'Metal', 'Future', 'Tech'] },

    // --- Actions ---
    { word: 'Run', forbidden: ['Walk', 'Fast', 'Jog', 'Legs', 'Speed'] },
    { word: 'Sleep', forbidden: ['Bed', 'Dream', 'Tired', 'Night', 'Eyes'] },
    { word: 'Cry', forbidden: ['Tears', 'Sad', 'Weep', 'Baby', 'Eyes'] },
    { word: 'Kiss', forbidden: ['Lips', 'Love', 'Mouth', 'Touch', 'French'] },
    { word: 'Dance', forbidden: ['Music', 'Move', 'Party', 'Club', 'Step'] },
    { word: 'Sing', forbidden: ['Song', 'Voice', 'Music', 'Microphone', 'Karaoke'] },
    { word: 'Swim', forbidden: ['Water', 'Pool', 'Ocean', 'Wet', 'Float'] },
    { word: 'Fly', forbidden: ['Bird', 'Plane', 'Air', 'Sky', 'Wings'] },
    { word: 'Cook', forbidden: ['Food', 'Kitchen', 'Chef', 'Eat', 'Make'] },
    { word: 'Read', forbidden: ['Book', 'Words', 'Page', 'Look', 'Learn'] },

    // --- Celebrities/India specific ---
    { word: 'Shah Rukh Khan', forbidden: ['King', 'Bollywood', 'Actor', 'Movie', 'Rahul'] },
    { word: 'Cricket', forbidden: ['Sport', 'Bat', 'Ball', 'India', 'Kohli'] },
    { word: 'Taj Mahal', forbidden: ['Agra', 'India', 'Marble', 'Wonder', 'Tomb'] },
    { word: 'Yoga', forbidden: ['Exercise', 'Stretch', 'Pose', 'Mat', 'Meditation'] },
    { word: 'Curry', forbidden: ['Indian', 'Spicy', 'Food', 'Sauce', 'Eat'] },
    { word: 'Bollywood', forbidden: ['Movie', 'India', 'Cinema', 'Dance', 'Film'] },
    { word: 'Ganges', forbidden: ['River', 'Holy', 'Water', 'India', 'Varanasi'] },
    { word: 'Saree', forbidden: ['Wear', 'Woman', 'Dress', 'Cloth', 'India'] },
    { word: 'Chai', forbidden: ['Tea', 'Drink', 'Milk', 'Hot', 'Cup'] },
    { word: 'Diwali', forbidden: ['Lights', 'Festival', 'India', 'Celebration', 'Crackers'] },

    // --- Abstract ---
    { word: 'Love', forbidden: ['Heart', 'Feeling', 'Like', 'Romance', 'Valentine'] },
    { word: 'Time', forbidden: ['Clock', 'Watch', 'Hour', 'Minute', 'Past'] },
    { word: 'Money', forbidden: ['Cash', 'Dollar', 'Buy', 'Spend', 'Rich'] },
    { word: 'Dream', forbidden: ['Sleep', 'Night', 'Bed', 'Imagine', 'Nightmare'] },
    { word: 'Secret', forbidden: ['Tell', 'Hide', 'Whisper', 'Keep', 'Quiet'] },
    { word: 'War', forbidden: ['Fight', 'Battle', 'Army', 'Gun', 'Peace'] },
    { word: 'Magic', forbidden: ['Trick', 'Wand', 'Wizard', 'Rabbit', 'Hat'] },
    { word: 'Luck', forbidden: ['Good', 'Bad', 'Chance', 'Fortune', 'Clover'] },
    { word: 'History', forbidden: ['Past', 'School', 'Subject', 'Learn', 'Time'] },
    { word: 'Future', forbidden: ['Past', 'Time', 'Tomorrow', 'Ahead', 'Predict'] }
];
